# Generated by Django 2.0.5 on 2018-08-20 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articlesApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article_Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_date_time', models.DateTimeField()),
                ('ending_date_time', models.DateTimeField()),
                ('state', models.CharField(choices=[('V', 'Vigente'), ('C', 'Caducado'), ('P', 'Perdido')], default='V', max_length=1, verbose_name='Estado')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articlesApp.Article')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
