# Generated by Django 2.0.5 on 2018-08-19 00:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articlesApp', '0002_auto_20180818_2122'),
        ('spacesApp', '0002_auto_20180818_2122'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservationsApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article_Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_date_time', models.DateTimeField()),
                ('ending_date_time', models.DateTimeField()),
                ('state', models.CharField(choices=[('A', 'Aceptado'), ('R', 'Rechazado'), ('P', 'Pendiente')], default='P', max_length=1, verbose_name='Estado')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articlesApp.Article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameModel(
            old_name='Reservation',
            new_name='Space_Reservation',
        ),
    ]
