# Generated by Django 2.0.5 on 2018-08-20 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spacesApp', '0002_auto_20180816_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='capacity',
            field=models.IntegerField(default=0),
        ),
    ]
