# Generated by Django 2.0.5 on 2018-08-20 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articlesApp', '0002_auto_20180816_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='capacity',
        ),
    ]
